/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RunsRouteRouteImport } from './routes/runs/route'
import { Route as EditorRouteRouteImport } from './routes/editor/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as R404IndexRouteImport } from './routes/404/index'
import { Route as RunSlugRouteImport } from './routes/run/$slug'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as EditorRunNewRouteImport } from './routes/editor/run/new'
import { Route as EditorRunRunIdRouteImport } from './routes/editor/run/$runId'

const RunsRouteRoute = RunsRouteRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRouteRoute = EditorRouteRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRouteRoute,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404IndexRoute = R404IndexRouteImport.update({
  id: '/404/',
  path: '/404/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunSlugRoute = RunSlugRouteImport.update({
  id: '/run/$slug',
  path: '/run/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRunNewRoute = EditorRunNewRouteImport.update({
  id: '/run/new',
  path: '/run/new',
  getParentRoute: () => EditorRouteRoute,
} as any)
const EditorRunRunIdRoute = EditorRunRunIdRouteImport.update({
  id: '/run/$runId',
  path: '/run/$runId',
  getParentRoute: () => EditorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRouteRouteWithChildren
  '/runs': typeof RunsRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/run/$slug': typeof RunSlugRoute
  '/404': typeof R404IndexRoute
  '/home': typeof HomeIndexRoute
  '/playground': typeof PlaygroundIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/editor/run/$runId': typeof EditorRunRunIdRoute
  '/editor/run/new': typeof EditorRunNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/run/$slug': typeof RunSlugRoute
  '/404': typeof R404IndexRoute
  '/home': typeof HomeIndexRoute
  '/playground': typeof PlaygroundIndexRoute
  '/runs': typeof RunsIndexRoute
  '/editor/run/$runId': typeof EditorRunRunIdRoute
  '/editor/run/new': typeof EditorRunNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRouteRouteWithChildren
  '/runs': typeof RunsRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/run/$slug': typeof RunSlugRoute
  '/404/': typeof R404IndexRoute
  '/home/': typeof HomeIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/editor/run/$runId': typeof EditorRunRunIdRoute
  '/editor/run/new': typeof EditorRunNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/runs'
    | '/auth/login'
    | '/auth/signup'
    | '/run/$slug'
    | '/404'
    | '/home'
    | '/playground'
    | '/runs/'
    | '/editor/run/$runId'
    | '/editor/run/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor'
    | '/auth/login'
    | '/auth/signup'
    | '/run/$slug'
    | '/404'
    | '/home'
    | '/playground'
    | '/runs'
    | '/editor/run/$runId'
    | '/editor/run/new'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/runs'
    | '/auth/login'
    | '/auth/signup'
    | '/run/$slug'
    | '/404/'
    | '/home/'
    | '/playground/'
    | '/runs/'
    | '/editor/run/$runId'
    | '/editor/run/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRouteRoute: typeof EditorRouteRouteWithChildren
  RunsRouteRoute: typeof RunsRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  RunSlugRoute: typeof RunSlugRoute
  R404IndexRoute: typeof R404IndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof RunsRouteRoute
    }
    '/playground/': {
      id: '/playground/'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404/': {
      id: '/404/'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$slug': {
      id: '/run/$slug'
      path: '/run/$slug'
      fullPath: '/run/$slug'
      preLoaderRoute: typeof RunSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/run/new': {
      id: '/editor/run/new'
      path: '/run/new'
      fullPath: '/editor/run/new'
      preLoaderRoute: typeof EditorRunNewRouteImport
      parentRoute: typeof EditorRouteRoute
    }
    '/editor/run/$runId': {
      id: '/editor/run/$runId'
      path: '/run/$runId'
      fullPath: '/editor/run/$runId'
      preLoaderRoute: typeof EditorRunRunIdRouteImport
      parentRoute: typeof EditorRouteRoute
    }
  }
}

interface EditorRouteRouteChildren {
  EditorRunRunIdRoute: typeof EditorRunRunIdRoute
  EditorRunNewRoute: typeof EditorRunNewRoute
}

const EditorRouteRouteChildren: EditorRouteRouteChildren = {
  EditorRunRunIdRoute: EditorRunRunIdRoute,
  EditorRunNewRoute: EditorRunNewRoute,
}

const EditorRouteRouteWithChildren = EditorRouteRoute._addFileChildren(
  EditorRouteRouteChildren,
)

interface RunsRouteRouteChildren {
  RunsIndexRoute: typeof RunsIndexRoute
}

const RunsRouteRouteChildren: RunsRouteRouteChildren = {
  RunsIndexRoute: RunsIndexRoute,
}

const RunsRouteRouteWithChildren = RunsRouteRoute._addFileChildren(
  RunsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRouteRoute: EditorRouteRouteWithChildren,
  RunsRouteRoute: RunsRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  RunSlugRoute: RunSlugRoute,
  R404IndexRoute: R404IndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
