export const EXPANDED_ELEVATION_GRAPH_HEIGHT = 200;
export const WIDGET_ANIMATION_DURATION = 0.2;
export const DEFAULT_FADE_IN_DURATION = 0.15;
export const DEFAULT_EASING = 'easeOut';
export const DEFAULT_SPRING_BOUNCE = 0.2;
